### ISSUE TITLE
Error: Cannot find module 'xtendui/tailwind.preset'

### ISSUE THREAD

**Issue by mehulkundu** [xtendui/xtendui#66]
While running in the Next.js framework, got this error on the first start up

In terminal

```
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
Error: Cannot find module 'xtendui/tailwind.preset'
Require stack:
.........
```

**Suggestion: Can anyone please provide a Next.js starter template with all of the Xtend UI features enabled**

**Comment by minimit** [comment]
Yea I'll do a boilerplate, btw did you install xtendui with `npm install xtendui --save` or `yarn add xtendui --save`.

**Comment by mehulkundu** [comment]
I did `npm install xtendui --save`

**Comment by minimit** [comment]
So in `postcss.config.js` nextjs uses it's own syntax.

```
module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': {},
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

**Comment by mehulkundu** [comment]
I also used the same 
Followed the [setup guide](https://xtendui.com/intro/setup) step by step

**Comment by minimit** [comment]
I did too and I don't have that problem, added boilerplate example check it out https://github.com/xtendui/xtendui-boilerplate/tree/v1.0.14.1/nextjs

**Comment by mehulkundu** [comment]
But you didn't add GSAP and Polyfill
Can you add that too or maybe create another extensive template with both of them

And a unstyled version of it would be greatly helpful as well.

So basically 4 templates - 
**next-extend-styled**
**next-extend-unstyled**
**next-extend-styled-all**   `#having GSAP and Polyfill configured`
**next-extend-unstyled-all**    `#having GSAP and Polyfill configured`

**Comment by minimit** [comment]
I didn't add polyfills because Nextjs has problems with [transpiling inside `node_modules`](https://github.com/vercel/next.js/discussions/32223) and with [using `.browserslistrc`](https://github.com/vercel/next.js/discussions/12826), so there's no babel in this code, I'll wait for this to work properly. if you want to polyfill correctly you can use [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules).

For gsap you can use normally just if you use **gsap plugins** remember to **fix SSR errors** by checking `window`.

```js
if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollToPlugin)
}
```

I've updated docs and boilerplate with this info and fixes some ssr errors on `src/form.js` and `src/usability`.
